spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  cloud:
    openfeign:
      client:
        config:
          feignName:
            connectTimeout: 5000
            readTimeout: 5000
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10 #10번 요청해서 실패율이 50%가 넘으면 서킷브레이커 open
        failureRateThreshold: 50 #10번 요청해서 실패율이 50%가 넘으면 서킷브레이커 open
        waitDurationInOpenState: 30s # 기본값(60s)보다 작게 설정하여 HALF_OPEN 상태로 빨리 전환되어 장애복구 시도
        slowCallDurationThreshold: 5s # 해당 값은 TimeLimiter의 timeoutDuration보다 작아야 함
        registerHealthIndicator: true
        recordFailurePredicate: com.example.searchplace.feign.RecordFailurePredicate
    instances:
      default:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 6s # slowCallDurationThreshold보다는 크게 설정
        cancelRunningFuture: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#개인설정 값
searchplace:
  feign:
    kakao:
      name: kakao
      url: https://dapi.kakao.com
      header1:
        key: Authorization
        value: ENC(ONWMWajeg0t6JoNu5Yn9sMsziRZmcLcH4QFRVxnV3J1nzB2Q33EZyUpVCZvbbpFoAP7B328o9b0=)
    naver:
      name: naver
      url: https://openapi.naver.com
      header1:
        key: X-Naver-Client-Id
        value: ENC(Dj6/805wlH4U22sqLqM1UXbF2urG8JWoxRBzgyOKjUA=)
      header2:
        key: X-Naver-Client-Secret
        value: ENC(qhE5zePYojJc9XBLGbqqmbxJp5Pl2evD)
    keywordList:
      name: keyword
      url: http://localhost:8081